### ISSUE TITLE
Test build icon shows failing depsite tests are passing

### ISSUE THREAD

**Issue by alebonfanti** [JuliaRheology/RHEOSafm.jl#1]
Sometimes the build icon for test reports "error" despite all test passed. 
It seems a problem that several people are having:
https://github.com/travis-ci/travis-ci/issues/8389

**Comment by moustachio-belvedere** [comment]
Main RHEOS also seems to have it sometimes too

**Comment by WolfgangFahl** [comment]
The other issue seems to have been closed but I can't see how it was resolved.

**Comment by moustachio-belvedere** [comment]
This seems to be fixed now 👍
